### ISSUE TITLE
Android application crash issue on back press 

### ISSUE THREAD

**Issue by achint1992** [NeoSmartpen/AndroidSDK2.0#1]
Hi Guys,

I am using the ANDROID SDK 2.0 but I saw some major issues in it. First application kills after pressing back on main activity. Please put any activity before Main Activity you will be able to check the issue.

It kills all activities which are in background and in such a way application will crash on mobile. I am Getting following crash error over the application.
 DotConsumerThread Interrupted!!java.lang.InterruptedException

This new Android SDK code renders data more slower than previous SurfaceView Example in your sample.

Please have a look over the points that I mentioned.

Waiting for your response.

Regards,
Achint Sarkar

**Comment by mrlove1** [comment]
Hi achint1992.

First application kills after pressing back on main activity.
-> I don't understand your comment.
Main Activity of Sample source destroy Service.  Are you saying that?
What is First application? I expect you to explain it to me in detail.

DotConsumerThread Interrupted!!
-> It does not have to matter.
It's just code to prevent the DotConsumerThread from running continuously.
(mDotQueueForBroadcast.wait();)

This new Android SDK code renders data more slower than previous SurfaceView Example in your sample.
-> SurfaceView takes up too much resources. Because SurfaceView  runs continuously.
You can modify the sample source if you want.

Sample is only just Sample .
If you want, you can always modify and develop it.

Thanks you.
Best Regards,
Moosaeng

**Comment by achint1992** [comment]
Hi,

Check your sample code.

Create one activity and launch main activity with out finish it.

Now you will come on main activity.

Now press back button of android.

Application is force fully closed. I am getting this issue over Samsung
galaxy s6.

Please have a look over it .

Regards,
Achint sarkar

**Comment by achint1992** [comment]
Hi,

I am not getting any crash logs on it and application is totally killed.
Even not able to monitor memory heaps over this even.

Regards,
Achint sarkar

**Comment by mrlove1** [comment]
Hi Achint sarkar.

Sample code app kill another app when Sample code app destroy?
I still do't understand.
If you send me Apk or your source, i will test or check it tomorrow morning.

Best Regard,
Moosaemg.



2017-04-18 19:55 GMT+09:00 achint1992 <notifications@github.com>:

> Hi,
>
> I am not getting any crash logs on it and application is totally killed.
> Even not able to monitor memory heaps over this even.
>
> Regards,
> Achint sarkar
>

**Comment by achint1992** [comment]
Hi,



Please have a look on code. I am not talking about two application. I am
talking about same application having two activities.

*In this code Main​​2Activity.java is launcher activity. and it launches
another activity MainActivity.java.*

*On Finishing MainActivity.java it kill over all application where it
should go back to Main2Activity.java.*

Its Killing the sample application itself, and i am getting no crash issue
over it.

Regards,
Achint Sarkar

​
 NASDK2.0_sample_code.zip
<https://drive.google.com/file/d/0B5DEleZv0EFhaXFFaGV5SmVFZUU/view?usp=drive_web>
​

**Comment by mrlove1** [comment]
Hi Achint sarkar.

This is not crash.
This is just sample source UI flow .

MainActivity stop Service when MainActivity destroy.
Service run "android.os.Process.killProcess( android.os.Process.myPid() );" when Service destroy.

If you don't want this flow, would you use it to modify it please?

If it was me, i don't stop Service when MainActivity destroy.
Or  i don't run "android.os.Process.killProcess( android.os.Process.myPid() );"  when Service destroy.

We provide NeoSDK and Sample source by free.
If the NeoSDK have trouble or crash , i will always help developer.
But I could not modify the SDK sample source as you like.
You must modify sample source.

This issue closed.
Thanks.
Best Regards,
Moosaeng
