### ISSUE TITLE
.nproj file

### ISSUE THREAD

**Issue by aykuttasil** [NeoSmartpen/AndroidSDK2.0#11]
Hi,
I need to a .nproj file for test. But i didn't find in sample project.
How can I get this file?

**Comment by mrlove1** [comment]
Hi,
What paper' nproj file do you want?
First, i upload the Ring note file(section 3,owner 27, book 603).
(AndroidSDK2.0/NASDK2.0_sample_code/NASDK_sample_code/src/main/assets/note_0603.nproj)
If you tell me the nproj file you want, I will upload it.
Thanks.
Best Regards,
Moosaeng Lim

**Comment by aykuttasil** [comment]
Can you upload the 571 book code? (section 3,owner 27, book 571)
Thank you.

**Comment by mrlove1** [comment]
Hi,

We have never issued the note(section 3,owner 27, book 571).

Do you have the Note(section 3,owner 27, book 571)?

Let me know your company's name.

Thanks.
Best Regards,
Moosaeng Lim
