### ISSUE TITLE
Regarding filling forms to be printed

### ISSUE THREAD

**Issue by shubhambhartiya** [NeoSmartpen/AndroidSDK2.0#2]
Hello there,
I have a small query regarding the whole process. 
According to my understanding and information given on the website, we need a paper that would be printed with some unique coding and when the pen writes on it, the pen would send the data to lets say android via Bluetooth and then the app would send the data to servers. I have some questions regarding the process: 
1) Can the encoded pages through some software or someone has to source the pages
2) Will the app get plain text response or will have to be decoded from some format
I am eagerly awaiting for your response.
Regards

**Comment by NeolabConvergence** [comment]
Hi shubhambhartiya,

Thanks for your interest in our products.

**Answer:**

1. Can the encoded pages through some software or someone has to source the pages
>> Please see the attached image first, and ask again.

2. Will the app get plain text response or will have to be decoded from some format
>>1) An app will receive a decoded stroke data from Pen SDK. (stroke data is xy coord array)
>>2) If you need to convert handwriting stroke data to text, you should use text recognition engine.
>>    (ex. MyScript or other cloud text recognition API)

image1:
---
![01_overall process for service development](https://cloud.githubusercontent.com/assets/9605274/25419372/245a0752-2a8d-11e7-8acb-ad0b701536f7.png)
---
image2:
---
![02_overall process for service development more detail](https://cloud.githubusercontent.com/assets/9605274/25419373/245c4972-2a8d-11e7-8fec-79cae7fec3af.png)
--
