### ISSUE TITLE
Does the noteId have anything to do with plotting the coordinates?

### ISSUE THREAD

**Issue by wushangjun** [NeoSmartpen/AndroidSDK2.0#3]
The book provided by the merchant cannot be drawn on the demo

**Comment by mrlove1** [comment]
No, Section id, Owner id , note Id(book code) is for categorization.

And i don't know cause cannot be drawn on the demo.

I want you explain me detail.

Thank you

Best Regards,
Moosaeng

**Comment by mrlove1** [comment]
if do not you have any more question, this issue is closed.
