### ISSUE TITLE
Hello. Can you tell me if you can click the button to play back your handwriting?

### ISSUE THREAD

**Issue by wushangjun** [NeoSmartpen/AndroidSDK2.0#4]

**Comment by mrlove1** [comment]
Is it replay function that you say?

Our refrence App 'NeoNotes' have replay function.

And you can implement replay function.

Draw strokes over time  from start_timestamp of first stroke  to end_timestamp of end stroke .

Thank you

Best Regards,
Moosaeng

**Comment by wushangjun** [comment]
Please tell me how to set the pen's thickness?

**Comment by wushangjun** [comment]
Hello, can replay provide demo? I don't quite understand, thank you

**Comment by mrlove1** [comment]
Hi wushangjun.

We provide basic sample source  only.

But if you need source what includes special function, discuss to the Global business team.

Contact url is "https://neosmartpen.freshdesk.com/support/tickets/new".

Choose category "B2B solution inquires".

Thanks.

Best Regards,
Moosaeng

**Comment by mrlove1** [comment]
Hi wushangjun.

Pen's thickness

We provide basic sample source only.

But if you need source what includes special function, discuss to the Global business team.

Contact url is "https://neosmartpen.freshdesk.com/support/tickets/new".

Choose category "B2B solution inquires".

Thanks.

Best Regards,
Moosaeng

**Comment by mrlove1** [comment]
if do not you have any more question, this issue is closed.
