### ISSUE TITLE
Converting strokes 2 images

### ISSUE THREAD

**Issue by sreyansh57** [NeoSmartpen/AndroidSDK2.0#5]
Hi,

We are developing the application using the sample neosdk code for android.

We are facing the following issue while working offline:

1) While working offline and transferring data, we are getting strokes as the output.

Is there a way to convert strokes to image (png, bitmap or jpeg) without using canvas?

2) Is there a way to convert strokes to svg file?

Waiting for your reply.

Thanks,

Sreyansh choraria

**Comment by sreyansh57** [comment]
Please reply

**Comment by mrlove1** [comment]
Hi Sreyansh choraria.

1. We are converting to image from strokes by canvas.

2. You can convert to svg file from strokes.
We make svg file by using 'path' element.
And data(stroke color, thickness ...) save at custom attributes.
I attach the file. reference it  
Thanks.

Best Regard,
Moosaeng Lim.

[testSVG.zip](https://github.com/NeoSmartpen/AndroidSDK2.0/files/1154407/testSVG.zip)

**Comment by sreyansh57** [comment]
Hi,


Thank you for the reply.

Sorry but the reference file you have provided is contains only the SVG
file but no code for reference.


Please provide us with the code for the conversion process.


Thank you. Looking forward for your response.

Sreyansh choraria


On Jul 18, 2017 6:57 AM, "mrlove1" <notifications@github.com> wrote:

Hi Sreyansh choraria.

   1.

   We are converting to image from strokes by canvas.
   2.

   You can convert to svg file from strokes.
   We make svg file by using 'path' element.
   And data(stroke color, thickness ...) save at custom attributes.
   I attach the file. reference it
   Thanks.

Best Regard,
Moosaeng Lim.

testSVG.zip
<https://github.com/NeoSmartpen/AndroidSDK2.0/files/1154407/testSVG.zip>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NeoSmartpen/AndroidSDK2.0/issues/5#issuecomment-315931434>,
or mute the thread

**Comment by sreyansh57** [comment]
Please update us the code

**Comment by mrlove1** [comment]
Hi Sreyansh choraria.

We provide sample source about SDK only.

If you want to export svg file, you must search and develop by yourself.

But if you need source what includes special function, discuss to the Global business team.

Contact url is "https://neosmartpen.freshdesk.com/support/tickets/new".

Choose category "B2B solution inquires".

Thanks.

Best Regards,
Moosaeng

**Comment by mrlove1** [comment]
if do not you have any more question, this issue is closed.
