### ISSUE TITLE
How do I get the electricity?

### ISSUE THREAD

**Issue by wushangjun** [NeoSmartpen/AndroidSDK2.0#6]
How do I get the electricity?
Thanks

**Comment by mrlove1** [comment]
Hi wushangjun.

Does "the electricity" means Pen device?

Or do you ask me about recharging?

I don't understand.

Explain me in detail, please.

Thanks.

Best Regards,
Moosaeng.

**Comment by mrlove1** [comment]
if do not you have any more question, this issue is closed.
