### ISSUE TITLE
Auto-On function of Smartpen not working

### ISSUE THREAD

**Issue by SouravJ** [NeoSmartpen/AndroidSDK2.0#7]
Hi, 
Auto-on function of smartpen is not working with neo notes app as well as ncode sdk.
Could you please let me know how to resolve it?

**Comment by mrlove1** [comment]
Hi SouravJ,

I need a detailed explanation.

what is model name of your pen?

Here is how to turn on Auto-on function.

1. request
IPenCtrl.reqSetupAutoPowerOnOff(true);

2. Check setting
2-1. request status
IPenCtrl.reqPenStatus()
2-2. result check
(SDK sample - PenClientCtrl class - onReceiveMessage method)
 case PenMsgType.PEN_STATUS:
	JSONObject job = penMsg.getContentByJSONObject();
	boolean stat_autopower = job.getBoolean( Const.JsonTag.BOOL_AUTO_POWER_ON );
stat_autopower value check!!!

do it like above.
if it still doesn't work, send me Full Log(about request and status result).

Thanks,

Best,
Moosaeng.

**Comment by mrlove1** [comment]
if do not you have any more question, this issue is closed.
