### ISSUE TITLE
Android SDK 2.0 빌드 문의

### ISSUE THREAD

**Issue by eudj465** [NeoSmartpen/AndroidSDK2.0#8]
안녕하세요 G7 ICT R&D 입니다.
NASDK2.0_sample_code를 빌드하는 과정에서 오류가 생겨서 문의드립니다.
아래 사진과 같이 빌드 버튼이 활성화가 안되며, layout Design을 확인 할 수 없습니다.

![nasdk2 0_sample_code](https://user-images.githubusercontent.com/29448775/29952077-14b84ce4-8f02-11e7-80ff-d12e64a2dae7.png)

빌드하기 위한 세팅법 및 오류해결 방법을 eudj465@gmail.com 으로 알려주시겠습니까?
답변 기다리겠습니다.
감사합니다.

**Comment by mrlove1** [comment]
안녕하세요

gitHub 에서 직접 다운로드 받아 스튜디오에서 오픈하였으나 전혀 문제가 없습니다.

혹시나 하여 SDK 의 경로가 직접경로로 되어 있는데 상대경로로 바꾸어 올려두긴 했습니다.

설마 그거때문에 문의를 주신듯하지는 않고 위 스크린샷만으로는 답변을 드리기가 힘듭니다.

전화를 드렸으나 받지 않으셔서 여기에 답변 남깁니다.

감사합니다.
